spring:
  mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: kihdwyy@163.com  # 开启那个服务的邮箱
    password: CUhjK4tZ94BDrRHT  # 开启服务的那个认证码
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
mail:
  address: kihdwyy@163.com # 开启那个服务的邮箱

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl